@baseURL = http://localhost:3000
@pollId = 75da2c40-fc59-4378-9059-b0887a7cf883

# poll: Quantos anos eu tenho?
GET {{baseURL}}/polls/{{pollId}}

###

POST @baseURL/polls/

{
    "title":"Quantos anos eu tenho?",
    "options": ["12", "21", "25", "22"]
}

###

POST {{baseURL}}/polls/{{pollId}}/votes/

{
    "optionId": "81aab8f0-97a5-4fcd-a7bd-bebe75cc4b58"
}
